name: copilot-deploy-infra

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_OPENAI_ENDPOINT:
        required: true
    outputs:
      deployment-id:
        description: "The Id of the current deployment."
        value: "app-copichat-rlvquxqizayf2-webapi.azurewebsites.net"

jobs:
  deploy:
    environment: ${{inputs.ENVIRONMENT}}
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: ubuntu-latest }
    outputs:
      deployment-id: ${{steps.deployment-id.outputs.deployment_name}}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Generate Deployment Id
        id: deployment-id
        run: echo "deployment_name=${{ vars.CC_DEPLOYMENT_NAME }}-$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT
